---
abstract: 'Namespace Class for Perl 5'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
build_requires:
  Data::Object::Name: '2.01'
  Test::Auto: '0.12'
  perl: '5.014'
  routines: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Object-Space
requires:
  Data::Object::Name: '2.01'
  perl: '5.014'
  routines: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/iamalnewkirk/data-object-space/issues
  homepage: https://metacpan.org/release/Data-Object-Space
  repository: git://github.com/iamalnewkirk/data-object-space.git
version: '2.06'
x_authority: cpan:AWNCORP
x_generated_by_perl: v5.30.1
x_serialization_backend: 'YAML::Tiny version 1.73'
