name: Testing

on:
  push:
    branches:
    - hotfix-*
    - issue-*
    - milestone-*
    - project-*
    - support-*

jobs:
  Perl-0000:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Git User
      run: git config --global user.name "Al Newkirk"
    - name: Setup Git Email
      run: git config --global user.email "awncorp@cpan.org"
    - name: Setup GitHub User
      run: git config --global github.user ${{ secrets.GithubUser }}
    - name: Setup GitHub Token
      run: git config --global github.user ${{ secrets.GithubToken }}
    - name: Install CPANM
      run: sudo apt install -y cpanminus
    - name: Install Perl::Critic
      run: sudo cpanm -qn Perl::Critic
    - name: Install Project Dependencies
      run: sudo cpanm -qn --reinstall --installdeps .
    - name: Critiquing Project
      run: perlcritic lib t
    - name: Testing Project
      run: prove -Ilib -r t
      env:
        HARNESS_OPTIONS: j9

  Perl-5163:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Perlbrew
      run: sudo apt install -y perlbrew
    - name: Initial Perlbrew
      run: sudo perlbrew init
    - name: Install CPANM
      run: sudo perlbrew install-cpanm
    - name: Install Perl 5.16
      run: sudo perlbrew install -n perl-5.16.3
    - name: Verify Perl Version
      run: sudo perlbrew exec --with perl-5.16.3 perl -V
    - name: Install Perl::Critic
      run: sudo perlbrew exec --with perl-5.16.3 cpanm -qn Perl::Critic
    - name: Install Perl Dependencies
      run: sudo perlbrew exec --with perl-5.16.3 cpanm -qn --reinstall --installdeps .
    - name: Critiquing Project
      run: sudo perlbrew exec --with perl-5.16.3 perlcritic lib t
    - name: Testing Project
      run: sudo perlbrew exec --with perl-5.16.3 prove -Ilib -r t
      env:
        HARNESS_OPTIONS: j9
